/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Twitter;

import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author Eduardo
 */
public class Twit extends javax.swing.JFrame {
    private static String currentUser="";
    private static String target="";
    public static Users usuarios = new Users();
    public static Twits twits = new Twits();
    public static Following follows = new Following();
    public static DefaultListModel<String> listmodel=new DefaultListModel();
    /**
     * Creates new form Twit
     */
    public Twit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        twit = new javax.swing.JPanel();
        menuinicio = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        signin = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        incorrecto = new javax.swing.JLabel();
        newUser = new javax.swing.JPanel();
        crearNombrecompleto = new javax.swing.JTextField();
        crearUsername = new javax.swing.JTextField();
        crearPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        crearMasculino = new javax.swing.JRadioButton();
        crearFemenino = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        crearCuenta = new javax.swing.JButton();
        crearRegresar = new javax.swing.JButton();
        llenarcampos = new javax.swing.JLabel();
        crearEdad = new javax.swing.JSpinner();
        menuPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenido = new javax.swing.JTextArea();
        send = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        salirTwit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        myMentions = new javax.swing.JTextPane();
        buscarUser = new javax.swing.JTextField();
        editProfile = new javax.swing.JLabel();
        cantidadCaracteres = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listausuarios = new javax.swing.JList<>();
        buscarProfile = new javax.swing.JPanel();
        Twitregresar = new javax.swing.JButton();
        FollowUnfollow = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        buscarTweets = new javax.swing.JTextPane();
        targetFollowers = new javax.swing.JLabel();
        targetFollowing = new javax.swing.JLabel();
        nombreTarget = new javax.swing.JLabel();
        targetisFollowing = new javax.swing.JLabel();
        MiPerfil = new javax.swing.JPanel();
        timelineRegresar = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        menciones = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        myFollowing = new javax.swing.JLabel();
        myUsername = new javax.swing.JLabel();
        myFollowers = new javax.swing.JLabel();
        desactivarCuenta = new javax.swing.JButton();
        myAntiquity = new javax.swing.JLabel();
        irAHashtags = new javax.swing.JButton();
        placeholderMenuPrincipal = new javax.swing.JPanel();
        timeline = new javax.swing.JButton();
        mandartweet = new javax.swing.JButton();
        editarPerfil = new javax.swing.JButton();
        buscarHash = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayUsuario = new javax.swing.JTextArea();
        buscarHashtags = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        buscarHashtagTweets = new javax.swing.JTextPane();
        hashRegresar = new javax.swing.JButton();
        buscarhash = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        twit.setLayout(new java.awt.CardLayout());

        menuinicio.setOpaque(false);

        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setText("Usuario");

        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password.setText("Contraseña");

        signin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signin.setText("Sign in");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });

        signup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signup.setText("Sign Up");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        incorrecto.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout menuinicioLayout = new javax.swing.GroupLayout(menuinicio);
        menuinicio.setLayout(menuinicioLayout);
        menuinicioLayout.setHorizontalGroup(
            menuinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuinicioLayout.createSequentialGroup()
                .addGroup(menuinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuinicioLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(incorrecto))
                    .addGroup(menuinicioLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(menuinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menuinicioLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(signin)
                        .addGap(18, 18, 18)
                        .addComponent(signup)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        menuinicioLayout.setVerticalGroup(
            menuinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuinicioLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(incorrecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menuinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signin)
                    .addComponent(signup))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        twit.add(menuinicio, "card2");

        crearNombrecompleto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        crearNombrecompleto.setText("Nombre Completo");

        crearUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        crearUsername.setText("Username");

        crearPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        crearPassword.setText("Contraseña");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Edad");

        buttonGroup1.add(crearMasculino);
        crearMasculino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        crearMasculino.setText("M");
        crearMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearMasculinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(crearFemenino);
        crearFemenino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        crearFemenino.setText("F");
        crearFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearFemeninoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Genero");

        crearCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crearCuenta.setText("Crear Cuenta");
        crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaActionPerformed(evt);
            }
        });

        crearRegresar.setText("Regresar");
        crearRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearRegresarActionPerformed(evt);
            }
        });

        llenarcampos.setForeground(new java.awt.Color(255, 0, 0));
        llenarcampos.setText(" ");

        crearEdad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        crearEdad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout newUserLayout = new javax.swing.GroupLayout(newUser);
        newUser.setLayout(newUserLayout);
        newUserLayout.setHorizontalGroup(
            newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserLayout.createSequentialGroup()
                        .addComponent(crearRegresar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserLayout.createSequentialGroup()
                        .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(newUserLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(50, 50, 50))
                            .addGroup(newUserLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(37, 37, 37)))
                        .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newUserLayout.createSequentialGroup()
                                .addComponent(crearMasculino)
                                .addGap(89, 89, 89)
                                .addComponent(crearFemenino))
                            .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(crearNombrecompleto)
                                .addComponent(crearUsername)
                                .addComponent(crearPassword)
                                .addComponent(crearEdad)))
                        .addGap(243, 243, 243))))
            .addGroup(newUserLayout.createSequentialGroup()
                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newUserLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(llenarcampos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newUserLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(crearCuenta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newUserLayout.setVerticalGroup(
            newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(crearNombrecompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(crearUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(crearPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addComponent(llenarcampos)
                .addGap(18, 18, 18)
                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crearFemenino)
                    .addComponent(jLabel6)
                    .addComponent(crearMasculino))
                .addGap(37, 37, 37)
                .addComponent(crearCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(crearRegresar)
                .addContainerGap())
        );

        twit.add(newUser, "card3");

        contenido.setColumns(20);
        contenido.setRows(5);
        contenido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contenidoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(contenido);
        contenido.setLineWrap(true);
        contenido.setWrapStyleWord(true);

        send.setText("Mandar Tweet");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        salirTwit.setText("Salir de Twit");
        salirTwit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirTwitActionPerformed(evt);
            }
        });

        myMentions.setEditable(false);
        myMentions.setBorder(null);
        jScrollPane3.setViewportView(myMentions);

        buscarUser.setText("Buscar usuario");
        buscarUser.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                buscarUserInputMethodTextChanged(evt);
            }
        });
        buscarUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarUserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarUserKeyReleased(evt);
            }
        });

        editProfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editProfile.setText("Mi Perfil");
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProfileMouseExited(evt);
            }
        });

        cantidadCaracteres.setText("0/140");

        listausuarios.setModel(listmodel);
        listausuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listausuariosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listausuarios);

        javax.swing.GroupLayout menuPrincipalLayout = new javax.swing.GroupLayout(menuPrincipal);
        menuPrincipal.setLayout(menuPrincipalLayout);
        menuPrincipalLayout.setHorizontalGroup(
            menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPrincipalLayout.createSequentialGroup()
                        .addComponent(cerrarSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirTwit))
                    .addGroup(menuPrincipalLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(menuPrincipalLayout.createSequentialGroup()
                                .addComponent(cantidadCaracteres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(send))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarUser, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editProfile)))))
                .addContainerGap())
        );
        menuPrincipalLayout.setVerticalGroup(
            menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(send)
                            .addComponent(cantidadCaracteres))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPrincipalLayout.createSequentialGroup()
                        .addComponent(buscarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editProfile)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cerrarSesion)
                    .addComponent(salirTwit))
                .addContainerGap())
        );

        twit.add(menuPrincipal, "card4");

        Twitregresar.setText("Regresar");
        Twitregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwitregresarActionPerformed(evt);
            }
        });

        FollowUnfollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FollowUnfollowActionPerformed(evt);
            }
        });

        buscarTweets.setEditable(false);
        buscarTweets.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane5.setViewportView(buscarTweets);

        targetFollowers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        targetFollowers.setText("Followers: ");

        targetFollowing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        targetFollowing.setText("Following: ");

        nombreTarget.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombreTarget.setText("User");

        targetisFollowing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        targetisFollowing.setText("isFollowing");

        javax.swing.GroupLayout buscarProfileLayout = new javax.swing.GroupLayout(buscarProfile);
        buscarProfile.setLayout(buscarProfileLayout);
        buscarProfileLayout.setHorizontalGroup(
            buscarProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscarProfileLayout.createSequentialGroup()
                        .addComponent(Twitregresar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscarProfileLayout.createSequentialGroup()
                        .addGroup(buscarProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FollowUnfollow, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(buscarProfileLayout.createSequentialGroup()
                                .addComponent(targetFollowers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(buscarProfileLayout.createSequentialGroup()
                                .addComponent(targetFollowing)
                                .addGap(524, 524, 524)))
                        .addGap(123, 123, 123))
                    .addGroup(buscarProfileLayout.createSequentialGroup()
                        .addComponent(nombreTarget)
                        .addGap(145, 145, 145)
                        .addComponent(targetisFollowing)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        buscarProfileLayout.setVerticalGroup(
            buscarProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarProfileLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(buscarProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscarProfileLayout.createSequentialGroup()
                        .addComponent(targetisFollowing)
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buscarProfileLayout.createSequentialGroup()
                        .addComponent(nombreTarget)
                        .addGap(35, 35, 35)
                        .addComponent(targetFollowers)
                        .addGap(74, 74, 74)
                        .addComponent(targetFollowing)))
                .addGap(18, 18, 18)
                .addComponent(FollowUnfollow, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(Twitregresar)
                .addContainerGap())
        );

        twit.add(buscarProfile, "card5");

        timelineRegresar.setText("Regresar");
        timelineRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timelineRegresarActionPerformed(evt);
            }
        });

        menciones.setEditable(false);
        menciones.setBorder(null);
        jScrollPane7.setViewportView(menciones);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Interacciones");

        myFollowing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myFollowing.setText("Following: ");

        myUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myUsername.setForeground(new java.awt.Color(0, 0, 255));
        myUsername.setText("User");

        myFollowers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myFollowers.setText("Followers: ");

        desactivarCuenta.setText("Desactivar Cuenta");
        desactivarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactivarCuentaActionPerformed(evt);
            }
        });

        myAntiquity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myAntiquity.setText("Miembro desde: ");

        irAHashtags.setText("Buscar Hastags");
        irAHashtags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irAHashtagsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MiPerfilLayout = new javax.swing.GroupLayout(MiPerfil);
        MiPerfil.setLayout(MiPerfilLayout);
        MiPerfilLayout.setHorizontalGroup(
            MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiPerfilLayout.createSequentialGroup()
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(timelineRegresar)
                        .addGap(100, 100, 100)
                        .addComponent(myAntiquity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(desactivarCuenta))
                    .addGroup(MiPerfilLayout.createSequentialGroup()
                        .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MiPerfilLayout.createSequentialGroup()
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(myFollowers)
                                            .addComponent(myFollowing)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(irAHashtags)))
                            .addGroup(MiPerfilLayout.createSequentialGroup()
                                .addGap(306, 306, 306)
                                .addComponent(myUsername)))
                        .addGap(0, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MiPerfilLayout.setVerticalGroup(
            MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myUsername)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MiPerfilLayout.createSequentialGroup()
                        .addComponent(myFollowers)
                        .addGap(18, 18, 18)
                        .addComponent(myFollowing)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(irAHashtags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timelineRegresar)
                    .addComponent(desactivarCuenta)
                    .addComponent(myAntiquity))
                .addContainerGap())
        );

        twit.add(MiPerfil, "card6");

        timeline.setText("Time Line");
        timeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timelineActionPerformed(evt);
            }
        });

        mandartweet.setText("Mandar tweet");
        mandartweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mandartweetActionPerformed(evt);
            }
        });

        editarPerfil.setText("Editar Profile");

        buscarHash.setText("Buscar hastags");

        displayUsuario.setEditable(false);
        displayUsuario.setColumns(20);
        displayUsuario.setRows(5);
        jScrollPane2.setViewportView(displayUsuario);

        javax.swing.GroupLayout placeholderMenuPrincipalLayout = new javax.swing.GroupLayout(placeholderMenuPrincipal);
        placeholderMenuPrincipal.setLayout(placeholderMenuPrincipalLayout);
        placeholderMenuPrincipalLayout.setHorizontalGroup(
            placeholderMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeholderMenuPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(placeholderMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buscarHash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mandartweet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(586, Short.MAX_VALUE))
            .addGroup(placeholderMenuPrincipalLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        placeholderMenuPrincipalLayout.setVerticalGroup(
            placeholderMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeholderMenuPrincipalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(timeline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mandartweet)
                .addGap(40, 40, 40)
                .addComponent(editarPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarHash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        twit.add(placeholderMenuPrincipal, "card7");

        jScrollPane5.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane5.setOpaque(false);
        jScrollPane5.setBackground(new Color(0,0,0,0));
        jScrollPane5.setViewportBorder(null);
        jScrollPane5.getViewport().setOpaque(false);
        jScrollPane5.getViewport().setBackground(new Color(0,0,0,0));

        buscarHashtagTweets.setEditable(false);
        buscarHashtagTweets.setBorder(null);
        jScrollPane6.setViewportView(buscarHashtagTweets);
        buscarTweets.setOpaque(false);
        buscarTweets.setBackground(new Color(0,0,0,0));

        hashRegresar.setText("Regresar");
        hashRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashRegresarActionPerformed(evt);
            }
        });

        buscarhash.setText("Buscar hashtag");
        buscarhash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarhashKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout buscarHashtagsLayout = new javax.swing.GroupLayout(buscarHashtags);
        buscarHashtags.setLayout(buscarHashtagsLayout);
        buscarHashtagsLayout.setHorizontalGroup(
            buscarHashtagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarHashtagsLayout.createSequentialGroup()
                .addGroup(buscarHashtagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscarHashtagsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hashRegresar))
                    .addGroup(buscarHashtagsLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(buscarHashtagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                            .addComponent(buscarhash))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        buscarHashtagsLayout.setVerticalGroup(
            buscarHashtagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarHashtagsLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(buscarhash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hashRegresar)
                .addContainerGap())
        );

        twit.add(buscarHashtags, "card8");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        twit.add(jPanel7, "card9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(twit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(twit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        username.setText(null);
        password.setText(null);
        Menu(newUser);
    }//GEN-LAST:event_signupActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        try{
            if(usuarios.login(username.getText(), password.getText())){
                currentUser=username.getText();
                username.setText(null);
                password.setText(null);
                actualizarTimeline();
                Menu(menuPrincipal);
            }else{
                int j = JOptionPane.showConfirmDialog(null, "Usuario o contraseña incorrecta.\nDesea crear un nuevo usario?");
                
                if(j==0){
                    username.setText(null);
                    password.setText(null);
                    Menu(newUser);
                }
            }
        }catch(IOException e){
            System.out.println("Error: "+e.getMessage());
        }
        catch(BadLocationException e){
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_signinActionPerformed

    private void crearFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearFemeninoActionPerformed

    private void crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaActionPerformed
        String nombre = crearNombrecompleto.getText();
        String user = crearUsername.getText();
        String pass = crearPassword.getText();
        int edad = (int)crearEdad.getValue();
        char genero=' ';
        
        if(!nombre.equals("") && !user.equals("") && !pass.equals("")
                 && (crearMasculino.isSelected() || crearFemenino.isSelected()))
        {   
            if(crearMasculino.isSelected()){
                genero='M';
            }else{
                genero = 'F';
            }
            try{
                if(!usuarios.buscarUser(crearUsername.getText())){
                    usuarios.crearUser(nombre, user, pass, edad, genero);
                    currentUser=user;
                    crearNombrecompleto.setText(null);
                    crearUsername.setText(null);
                    crearPassword.setText(null);
                    crearEdad.setValue(1);
                    llenarcampos.setText(" ");
                    buttonGroup1.clearSelection();
                    JOptionPane.showMessageDialog(null, "Usuario creado exitosamente");
                    Menu(menuPrincipal);
                }else{
                    JOptionPane.showMessageDialog(null, "Usuario ya existe");
                }
            }
            catch(IOException e){
                System.out.println("Error: "+e.getMessage());
                }

        }else{
            llenarcampos.setText("Se deben llenar todos los campos");
        }
    }//GEN-LAST:event_crearCuentaActionPerformed

    private void crearRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearRegresarActionPerformed
        crearNombrecompleto.setText(null);
        crearUsername.setText(null);
        crearPassword.setText(null);
        crearEdad.setValue(1);
        llenarcampos.setText(" ");
        buttonGroup1.clearSelection();
        Menu(menuinicio);
    }//GEN-LAST:event_crearRegresarActionPerformed

    private void crearMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearMasculinoActionPerformed

    private void salirTwitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirTwitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirTwitActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        try{
            buscarUser.setText("Buscar Usuario");
                //Borrar users del Jlist
                DefaultListModel<String> listModel2 = (DefaultListModel) listausuarios.getModel();
                listModel2.removeAllElements();
                displayUsuario.setText(usuarios.encontrarUsers(buscarUser.getText(),currentUser));
                for(String s: usuarios.lista(buscarUser.getText(),currentUser)){
                    listModel2.addElement(s);
                }
        }catch(IOException e){
            System.out.println("Error; "+e.getMessage());
        }
        Menu(menuinicio);
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void mandartweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mandartweetActionPerformed
        Menu(buscarProfile);
    }//GEN-LAST:event_mandartweetActionPerformed

    private void TwitregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwitregresarActionPerformed
        try{
            actualizarTimeline();
            Menu(menuPrincipal);
        }catch(IOException e){
            System.out.println("error: "+e.getMessage());       
        }
        catch(BadLocationException e){
            System.out.println("error: "+e.getMessage());       
        }
    }//GEN-LAST:event_TwitregresarActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        try{
            if(usuarios.estadoCuenta(currentUser)){
                if(!contenido.getText().equals("")){
                    if(twits.mandarTweer(contenido.getText(), currentUser)){
                        JOptionPane.showMessageDialog(null, "Se mando un tweet");
                        contenido.setText(null);
                        actualizarTimeline();
                        Menu(menuPrincipal);
                    }else{
                        JOptionPane.showMessageDialog(null, "Tweet muy largo");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "No se puede mandar un tweet vacio");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Cuentas inactivas no pueden mandar tweets");
            }
        }catch(IOException e){
            System.out.println("Error: "+e.getMessage());
        }
        catch(BadLocationException e){
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_sendActionPerformed

    private void timelineRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timelineRegresarActionPerformed
        try{
            actualizarTimeline();
            Menu(menuPrincipal);
        }catch(IOException e){
            System.out.println("error: "+e.getMessage());       
        }
        catch(BadLocationException e){
            System.out.println("error: "+e.getMessage());       
        }
    }//GEN-LAST:event_timelineRegresarActionPerformed

    private void timelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timelineActionPerformed
        
    }//GEN-LAST:event_timelineActionPerformed

    private void buscarUserInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_buscarUserInputMethodTextChanged
        
    }//GEN-LAST:event_buscarUserInputMethodTextChanged

    private void buscarUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarUserKeyPressed
        
    }//GEN-LAST:event_buscarUserKeyPressed

    private void buscarUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarUserKeyReleased
        try{
            if(usuarios.estadoCuenta(currentUser)){
                //Borrar y poner users del Jlist
                DefaultListModel<String> listModel2 = (DefaultListModel) listausuarios.getModel();
                listModel2.removeAllElements();
                displayUsuario.setText(usuarios.encontrarUsers(buscarUser.getText(),currentUser));
                for(String s: usuarios.lista(buscarUser.getText(),currentUser)){
                    listModel2.addElement(s);
                }
            }
        }catch(IOException e){
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_buscarUserKeyReleased

    private void editProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseEntered
        editProfile.setForeground(new Color(0,0,200));
    }//GEN-LAST:event_editProfileMouseEntered

    private void editProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseExited
        editProfile.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_editProfileMouseExited

    private void editProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseClicked
        try{
            getMentions(currentUser);
            myFollowers.setText("Followers: "+follows.cantidadFollowers(currentUser));
            myFollowing.setText("Following: "+follows.cantidadFollowing(currentUser));
            myAntiquity.setText("Miembro desde: "+usuarios.getAntiquity(currentUser));
            myUsername.setText(currentUser);
            
            if(usuarios.estadoCuenta(currentUser))
                desactivarCuenta.setText("Desactivar Cuenta");
            else
                desactivarCuenta.setText("Activar Cuenta");
            Menu(MiPerfil);
        }catch(IOException e){
            System.out.println("error: "+e.getMessage());       
        }
        catch(BadLocationException e){
            System.out.println("error: "+e.getMessage());       
        }
        
    }//GEN-LAST:event_editProfileMouseClicked

    private void contenidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contenidoKeyReleased
        int cantidad = contenido.getText().length();
        if(cantidad>twits.caracteresMaximo)
            cantidadCaracteres.setForeground(Color.red);
        else
            cantidadCaracteres.setForeground(Color.black);
        
        cantidadCaracteres.setText(cantidad+"/"+twits.caracteresMaximo);
    }//GEN-LAST:event_contenidoKeyReleased

    private void listausuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listausuariosMouseClicked
        String nombre= listausuarios.getSelectedValue();
        
            try{
                if(!nombre.equals("")){
                    target=nombre;
                    getTweets(nombre);

                    if(follows.isFollowing(currentUser, target)){
                        FollowUnfollow.setText("Unfollow");
                    }else{
                        FollowUnfollow.setText("Follow");
                    }
                    listausuarios.clearSelection();
                    buscarUser.setText("Buscar Usuario");
                    //Borrar users del Jlist
                    DefaultListModel<String> listModel2 = (DefaultListModel) listausuarios.getModel();
                    listModel2.removeAllElements();
                    displayUsuario.setText(usuarios.encontrarUsers(buscarUser.getText(),currentUser));
                    for(String s: usuarios.lista(buscarUser.getText(),currentUser)){
                        listModel2.addElement(s);
                    }
                    targetFollowers.setText("Followers: "+follows.cantidadFollowers(target));
                    targetFollowing.setText("Following: "+follows.cantidadFollowing(target));
                    nombreTarget.setText("@"+target);
                    if(follows.isFollower(currentUser, target)){
                        targetisFollowing.setText(target+" te esta siguiendo");
                        targetisFollowing.setForeground(Color.blue);
                    }else{
                        targetisFollowing.setText(target+" no te esta siguiendo");
                        targetisFollowing.setForeground(Color.red);
                    }
                    Menu(buscarProfile);
                }
            }catch(IOException e){
                System.out.println("Error: "+e.getMessage());
            }
            catch(BadLocationException e){
                System.out.println("Error: "+e.getMessage());
            }
            catch(NullPointerException e){
                System.out.println("Ningun usuario seleccionado");
            }
        
    }//GEN-LAST:event_listausuariosMouseClicked

    private void FollowUnfollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FollowUnfollowActionPerformed
        try{
            
            if(follows.isFollowing(currentUser, target)){
                int j = JOptionPane.showConfirmDialog(null, "Seguro que quieres dejar de seguir a "+target+"?");
                
                if(j==0){
                    follows.followUnfollow(currentUser, target);
                    FollowUnfollow.setText("Follow");
                }
            }else{
                follows.followUnfollow(currentUser, target);
                FollowUnfollow.setText("UnFollow");
                }
            targetFollowers.setText("Followers: "+follows.cantidadFollowers(target));
            targetFollowing.setText("Following: "+follows.cantidadFollowing(target));
        }catch(IOException e){
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_FollowUnfollowActionPerformed

    private void hashRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashRegresarActionPerformed
        
            buscarHashtagTweets.setText("");
            Menu(MiPerfil);
        
    }//GEN-LAST:event_hashRegresarActionPerformed

    private void desactivarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactivarCuentaActionPerformed
        try{
            if(usuarios.estadoCuenta(currentUser)){
                int j = JOptionPane.showConfirmDialog(null, "Seguro que deseas desactivar la cuenta?");
                if(j==0){
                    usuarios.cambiarEstadoCuenta(currentUser);
                    desactivarCuenta.setText("Activar Cuenta");
                }
            }else{
                usuarios.cambiarEstadoCuenta(currentUser);
                desactivarCuenta.setText("Desactivar Cuenta");
            }
            getMentions(currentUser);
        }catch(IOException e){
            System.out.println("Esto no deberia pasar");
        }
        catch(BadLocationException e){
                System.out.println("Error: "+e.getMessage());
            }
    }//GEN-LAST:event_desactivarCuentaActionPerformed

    private void buscarhashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarhashKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!buscarhash.getText().equals("") || buscarhash.getText().contains(" ")){
                String hashtag = buscarhash.getText();

                try{
                    getHashTweets(hashtag);
                }catch(IOException e){
                System.out.println("Esto no deberia pasar");
                }
                catch(BadLocationException e){
                        System.out.println("Error: "+e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_buscarhashKeyReleased

    private void irAHashtagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irAHashtagsActionPerformed
        try{
            
            if(usuarios.estadoCuenta(currentUser)){
                Menu(buscarHashtags);
            buscarhash.setText("Buscar Hashtags");
            }else{
                JOptionPane.showMessageDialog(null, "Usuario inactivo");
            }
        
        }catch(IOException e){
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_irAHashtagsActionPerformed

    private void Menu(JPanel j){
        twit.removeAll();
        twit.add(j);
        twit.repaint();
        twit.revalidate();
    }
    
    private void actualizarTimeline()throws IOException, BadLocationException{
        myMentions.setText("");
        for(Tweet t: twits.timeLine(currentUser)){
            SimpleAttributeSet attributeSet = new SimpleAttributeSet();  
            StyleConstants.setBold(attributeSet, true);
            Document doc = myMentions.getStyledDocument();
            
            myMentions.setCharacterAttributes(attributeSet, true);
            doc.insertString(doc.getLength()," "+t.username+" escribio: \n" , attributeSet);
            StyleConstants.setBold(attributeSet, false);
            doc = myMentions.getStyledDocument();
            doc.insertString(doc.getLength()," \""+t.contenido+"\"\n" , attributeSet);
            attributeSet = new SimpleAttributeSet();
            StyleConstants.setFontSize(attributeSet, 9);
            StyleConstants.setItalic(attributeSet, true);
            doc = myMentions.getStyledDocument();
            doc.insertString(doc.getLength()," el "+t.fecha+"\n\n" , attributeSet);
        }
        myMentions.setCaretPosition(0);
        
    }
    
    private void getTweets(String user)throws IOException, BadLocationException{
        buscarTweets.setText("");
        for(Tweet t: twits.getTweets(user)){
            SimpleAttributeSet attributeSet = new SimpleAttributeSet();  
            StyleConstants.setBold(attributeSet, true);
            Document doc = buscarTweets.getStyledDocument();
            
            buscarTweets.setCharacterAttributes(attributeSet, true);
            doc.insertString(doc.getLength()," "+t.username+" escribio: \n" , attributeSet);
            StyleConstants.setBold(attributeSet, false);
            doc = buscarTweets.getStyledDocument();
            doc.insertString(doc.getLength()," \""+t.contenido+"\"\n" , attributeSet);
            attributeSet = new SimpleAttributeSet();
            StyleConstants.setFontSize(attributeSet, 9);
            StyleConstants.setItalic(attributeSet, true);
            doc = buscarTweets.getStyledDocument();
            doc.insertString(doc.getLength()," el "+t.fecha+"\n\n" , attributeSet);
        }
        buscarTweets.setCaretPosition(0);
        
    }
    
    private void getMentions(String user)throws IOException, BadLocationException{
        menciones.setText("");
        for(Tweet t: twits.getMentions(user)){
            SimpleAttributeSet attributeSet = new SimpleAttributeSet();  
            StyleConstants.setBold(attributeSet, true);
            Document doc = menciones.getStyledDocument();
            
            menciones.setCharacterAttributes(attributeSet, true);
            doc.insertString(doc.getLength()," "+t.username+" escribio: \n" , attributeSet);
            StyleConstants.setBold(attributeSet, false);
            doc = menciones.getStyledDocument();
            doc.insertString(doc.getLength()," \""+t.contenido+"\"\n" , attributeSet);
            attributeSet = new SimpleAttributeSet();
            StyleConstants.setFontSize(attributeSet, 9);
            StyleConstants.setItalic(attributeSet, true);
            doc = menciones.getStyledDocument();
            doc.insertString(doc.getLength()," el "+t.fecha+"\n\n" , attributeSet);
        }
        menciones.setCaretPosition(0);
        
    }
    
    private void getHashTweets(String hashtag)throws IOException, BadLocationException{
        buscarHashtagTweets.setText("");
        for(Tweet t: twits.getHash(hashtag)){
            SimpleAttributeSet attributeSet = new SimpleAttributeSet();  
            StyleConstants.setBold(attributeSet, true);
            Document doc = buscarHashtagTweets.getStyledDocument();
            
            buscarHashtagTweets.setCharacterAttributes(attributeSet, true);
            doc.insertString(doc.getLength()," "+t.username+" escribio: \n" , attributeSet);
            StyleConstants.setBold(attributeSet, false);
            doc = buscarHashtagTweets.getStyledDocument();
            doc.insertString(doc.getLength()," \""+t.contenido+"\"\n" , attributeSet);
            attributeSet = new SimpleAttributeSet();
            StyleConstants.setFontSize(attributeSet, 9);
            StyleConstants.setItalic(attributeSet, true);
            doc = buscarHashtagTweets.getStyledDocument();
            doc.insertString(doc.getLength()," el "+t.fecha+"\n\n" , attributeSet);
        }
        buscarHashtagTweets.setCaretPosition(0);
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Twit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Twit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Twit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Twit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Twit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FollowUnfollow;
    private javax.swing.JPanel MiPerfil;
    private javax.swing.JButton Twitregresar;
    private javax.swing.JButton buscarHash;
    private javax.swing.JTextPane buscarHashtagTweets;
    private javax.swing.JPanel buscarHashtags;
    private javax.swing.JPanel buscarProfile;
    private javax.swing.JTextPane buscarTweets;
    private javax.swing.JTextField buscarUser;
    private javax.swing.JTextField buscarhash;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cantidadCaracteres;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JTextArea contenido;
    private javax.swing.JButton crearCuenta;
    private javax.swing.JSpinner crearEdad;
    private javax.swing.JRadioButton crearFemenino;
    private javax.swing.JRadioButton crearMasculino;
    private javax.swing.JTextField crearNombrecompleto;
    private javax.swing.JTextField crearPassword;
    private javax.swing.JButton crearRegresar;
    private javax.swing.JTextField crearUsername;
    private javax.swing.JButton desactivarCuenta;
    private javax.swing.JTextArea displayUsuario;
    private javax.swing.JLabel editProfile;
    private javax.swing.JButton editarPerfil;
    private javax.swing.JButton hashRegresar;
    private javax.swing.JLabel incorrecto;
    private javax.swing.JButton irAHashtags;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList<String> listausuarios;
    private javax.swing.JLabel llenarcampos;
    private javax.swing.JButton mandartweet;
    private javax.swing.JTextPane menciones;
    private javax.swing.JPanel menuPrincipal;
    private javax.swing.JPanel menuinicio;
    private javax.swing.JLabel myAntiquity;
    private javax.swing.JLabel myFollowers;
    private javax.swing.JLabel myFollowing;
    private javax.swing.JTextPane myMentions;
    private javax.swing.JLabel myUsername;
    private javax.swing.JPanel newUser;
    private javax.swing.JLabel nombreTarget;
    private javax.swing.JTextField password;
    private javax.swing.JPanel placeholderMenuPrincipal;
    private javax.swing.JButton salirTwit;
    private javax.swing.JButton send;
    private javax.swing.JButton signin;
    private javax.swing.JButton signup;
    private javax.swing.JLabel targetFollowers;
    private javax.swing.JLabel targetFollowing;
    private javax.swing.JLabel targetisFollowing;
    private javax.swing.JButton timeline;
    private javax.swing.JButton timelineRegresar;
    private javax.swing.JPanel twit;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
